# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Frigobar Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: GitUser
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email aallysson0@gmail.com
          git config --global user.name Allysson Santos
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install project dependencies
        run: yarn --pure-lockfile --non-interactive
      - name: Run linters
        run: yarn lint
      - name: Run test
        run: yarn test
      - name: Publish
        run: |
          GH_TOKEN=${GH_TOKEN}
          NPM_TOKEN=${NPM_TOKEN}
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
          yarn lerna publish -y
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  documentation:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: GitUser
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email aallysson0@gmail.com
          git config --global user.name Allysson Santos
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install project dependencies
        run: yarn --pure-lockfile --non-interactive
      - name: Deploy documentation
        run: |
          CI=true
          yarn workspace @frigobar/documentation deploy
